# Generated by Django 4.1 on 2023-01-02 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0002_remove_task_list_list_tasks"),
    ]

    operations = [
        migrations.RemoveField(model_name="list", name="tasks",),
        migrations.AddField(
            model_name="task",
            name="list",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="lists.list"
            ),
        ),
    ]
