# Generated by Django 4.1 on 2023-01-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0005_list_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
