# Generated by Django 4.1 on 2023-01-18 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        ("lists", "0006_task_completed"),
    ]

    operations = [
        migrations.AlterModelOptions(name="task", options={"ordering": ["completed"]},),
        migrations.AddField(
            model_name="list",
            name="coowner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sharing",
                to="users.profile",
            ),
        ),
    ]
