# Generated by Django 4.1 on 2023-01-30 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0007_alter_task_options_list_coowner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
